[project]
name = "openstorm"
version = "0.1.0"
description = "CLI tool for managing local and production database instances via Docker."
authors = [
    {name = "Vlad Haidaichuk", email = "vlad.haidaichuk@gmail.com"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.19.2,<0.20.0",
    "pydantic-settings>=2.11.0,<3.0.0",
    "pymongo>=4.15.3,<5.0.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
openstorm = "openstorm.__main__:app"
